language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
notifications:
  recipients:
    - tyagi.kunal@live.com
  email:
    on_success: change
    on_failure: always
script:
  nosetests
os:
  - linux
